<?php

use Illuminate\Database\Seeder;

class TablaPaisesSeeder extends Seeder
{
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('paises')->truncate();

        $paises = [

            ['id'=>1, 'name'=>'Afganistán',   'created_at' => new DateTime ],
            ['id'=>2, 'name'=>'Albania',   'created_at' => new DateTime ],
            ['id'=>3, 'name'=>'Alemania',   'created_at' => new DateTime ],
            ['id'=>4, 'name'=>'Andorra',   'created_at' => new DateTime ],
            ['id'=>5, 'name'=>'Angola',   'created_at' => new DateTime ],
            ['id'=>6, 'name'=>'Antigua y Barbuda',   'created_at' => new DateTime ],
            ['id'=>7, 'name'=>'Arabia Saudita',   'created_at' => new DateTime ],
            ['id'=>8, 'name'=>'Argelia',   'created_at' => new DateTime ],
            ['id'=>9, 'name'=>'Argentina',   'created_at' => new DateTime ],
            ['id'=>10, 'name'=>'Armenia',   'created_at' => new DateTime ],
            ['id'=>11, 'name'=>'Australia',   'created_at' => new DateTime ],
            ['id'=>12, 'name'=>'Austria',   'created_at' => new DateTime ],
            ['id'=>13, 'name'=>'Azerbaiyán',   'created_at' => new DateTime ],
            ['id'=>14, 'name'=>'Bahamas',   'created_at' => new DateTime ],
            ['id'=>15, 'name'=>'Bangladés',   'created_at' => new DateTime ],
            ['id'=>16, 'name'=>'Barbados',   'created_at' => new DateTime ],
            ['id'=>17, 'name'=>'Baréin',   'created_at' => new DateTime ],
            ['id'=>18, 'name'=>'Bélgica',   'created_at' => new DateTime ],
            ['id'=>19, 'name'=>'Belice',   'created_at' => new DateTime ],
            ['id'=>20, 'name'=>'Benín',   'created_at' => new DateTime ],
            ['id'=>21, 'name'=>'Bielorrusia',   'created_at' => new DateTime ],
            ['id'=>22, 'name'=>'Birmania',   'created_at' => new DateTime ],
            ['id'=>23, 'name'=>'Bolivia',   'created_at' => new DateTime ],
            ['id'=>24, 'name'=>'Bosnia y Herzegovina',   'created_at' => new DateTime ],
            ['id'=>25, 'name'=>'Botsuana',   'created_at' => new DateTime ],
            ['id'=>26, 'name'=>'Brasil',   'created_at' => new DateTime ],
            ['id'=>27, 'name'=>'Brunéi',   'created_at' => new DateTime ],
            ['id'=>28, 'name'=>'Bulgaria',   'created_at' => new DateTime ],
            ['id'=>29, 'name'=>'Burkina Faso',   'created_at' => new DateTime ],
            ['id'=>30, 'name'=>'Burundi',   'created_at' => new DateTime ],
            ['id'=>31, 'name'=>'Bután',   'created_at' => new DateTime ],
            ['id'=>32, 'name'=>'Cabo Verde',   'created_at' => new DateTime ],
            ['id'=>33, 'name'=>'Camboya',   'created_at' => new DateTime ],
            ['id'=>34, 'name'=>'Camerún',   'created_at' => new DateTime ],
            ['id'=>35, 'name'=>'Canadá',   'created_at' => new DateTime ],
            ['id'=>36, 'name'=>'Catar',   'created_at' => new DateTime ],
            ['id'=>37, 'name'=>'Chad',   'created_at' => new DateTime ],
            ['id'=>38, 'name'=>'Chile',   'created_at' => new DateTime ],
            ['id'=>39, 'name'=>'China',   'created_at' => new DateTime ],
            ['id'=>40, 'name'=>'Chipre',   'created_at' => new DateTime ],
            ['id'=>41, 'name'=>'Ciudad del Vaticano',   'created_at' => new DateTime ],
            ['id'=>42, 'name'=>'Colombia',   'created_at' => new DateTime ],
            ['id'=>43, 'name'=>'Comoras',   'created_at' => new DateTime ],
            ['id'=>44, 'name'=>'Corea del Norte',   'created_at' => new DateTime ],
            ['id'=>45, 'name'=>'Corea del Sur',   'created_at' => new DateTime ],
            ['id'=>46, 'name'=>'Costa de Marfil',   'created_at' => new DateTime ],
            ['id'=>47, 'name'=>'Costa Rica',   'created_at' => new DateTime ],
            ['id'=>48, 'name'=>'Croacia',   'created_at' => new DateTime ],
            ['id'=>49, 'name'=>'Cuba',   'created_at' => new DateTime ],
            ['id'=>50, 'name'=>'Dinamarca',   'created_at' => new DateTime ],
            ['id'=>51, 'name'=>'Dominica',   'created_at' => new DateTime ],
            ['id'=>52, 'name'=>'Ecuador',   'created_at' => new DateTime ],
            ['id'=>53, 'name'=>'Egipto',   'created_at' => new DateTime ],
            ['id'=>54, 'name'=>'El Salvador',   'created_at' => new DateTime ],
            ['id'=>55, 'name'=>'Emiratos Árabes Unidos',   'created_at' => new DateTime ],
            ['id'=>56, 'name'=>'Eritrea',   'created_at' => new DateTime ],
            ['id'=>57, 'name'=>'Eslovaquia',   'created_at' => new DateTime ],
            ['id'=>58, 'name'=>'Eslovenia',   'created_at' => new DateTime ],
            ['id'=>59, 'name'=>'España',   'created_at' => new DateTime ],
            ['id'=>60, 'name'=>'Estados Unidos',   'created_at' => new DateTime ],
            ['id'=>61, 'name'=>'Estonia',   'created_at' => new DateTime ],
            ['id'=>62, 'name'=>'Etiopía',   'created_at' => new DateTime ],
            ['id'=>63, 'name'=>'Filipinas',   'created_at' => new DateTime ],
            ['id'=>64, 'name'=>'Finlandia',   'created_at' => new DateTime ],
            ['id'=>65, 'name'=>'Fiyi',   'created_at' => new DateTime ],
            ['id'=>66, 'name'=>'Francia',   'created_at' => new DateTime ],
            ['id'=>67, 'name'=>'Gabón',   'created_at' => new DateTime ],
            ['id'=>68, 'name'=>'Gambia',   'created_at' => new DateTime ],
            ['id'=>69, 'name'=>'Georgia',   'created_at' => new DateTime ],
            ['id'=>70, 'name'=>'Ghana',   'created_at' => new DateTime ],
            ['id'=>71, 'name'=>'Granada',   'created_at' => new DateTime ],
            ['id'=>72, 'name'=>'Grecia',   'created_at' => new DateTime ],
            ['id'=>73, 'name'=>'Guatemala',   'created_at' => new DateTime ],
            ['id'=>74, 'name'=>'Guyana',   'created_at' => new DateTime ],
            ['id'=>75, 'name'=>'Guinea',   'created_at' => new DateTime ],
            ['id'=>76, 'name'=>'Guinea ecuatorial',   'created_at' => new DateTime ],
            ['id'=>77, 'name'=>'Guinea-Bisáu',   'created_at' => new DateTime ],
            ['id'=>78, 'name'=>'Haití',   'created_at' => new DateTime ],
            ['id'=>79, 'name'=>'Honduras',   'created_at' => new DateTime ],
            ['id'=>80, 'name'=>'Hungría',   'created_at' => new DateTime ],
            ['id'=>81, 'name'=>'India',   'created_at' => new DateTime ],
            ['id'=>82, 'name'=>'Indonesia',   'created_at' => new DateTime ],
            ['id'=>83, 'name'=>'Irak',   'created_at' => new DateTime ],
            ['id'=>84, 'name'=>'Irán',   'created_at' => new DateTime ],
            ['id'=>85, 'name'=>'Irlanda',   'created_at' => new DateTime ],
            ['id'=>86, 'name'=>'Islandia',   'created_at' => new DateTime ],
            ['id'=>87, 'name'=>'Islas Marshall',   'created_at' => new DateTime ],
            ['id'=>88, 'name'=>'Islas Salomón',   'created_at' => new DateTime ],
            ['id'=>89, 'name'=>'Israel',   'created_at' => new DateTime ],
            ['id'=>90, 'name'=>'Italia',   'created_at' => new DateTime ],
            ['id'=>91, 'name'=>'Jamaica',   'created_at' => new DateTime ],
            ['id'=>92, 'name'=>'Japón',   'created_at' => new DateTime ],
            ['id'=>93, 'name'=>'Jordania',   'created_at' => new DateTime ],
            ['id'=>94, 'name'=>'Kazajistán',   'created_at' => new DateTime ],
            ['id'=>95, 'name'=>'Kenia',   'created_at' => new DateTime ],
            ['id'=>96, 'name'=>'Kirguistán',   'created_at' => new DateTime ],
            ['id'=>97, 'name'=>'Kiribati',   'created_at' => new DateTime ],
            ['id'=>98, 'name'=>'Kuwait',   'created_at' => new DateTime ],
            ['id'=>99, 'name'=>'Laos',   'created_at' => new DateTime ],
            ['id'=>100, 'name'=>'Lesoto',   'created_at' => new DateTime ],
            ['id'=>101, 'name'=>'Letonia',   'created_at' => new DateTime ],
            ['id'=>102, 'name'=>'Líbano',   'created_at' => new DateTime ],
            ['id'=>103, 'name'=>'Liberia',   'created_at' => new DateTime ],
            ['id'=>104, 'name'=>'Libia',   'created_at' => new DateTime ],
            ['id'=>105, 'name'=>'Liechtenstein',   'created_at' => new DateTime ],
            ['id'=>106, 'name'=>'Lituania',   'created_at' => new DateTime ],
            ['id'=>107, 'name'=>'Luxemburgo',   'created_at' => new DateTime ],
            ['id'=>108, 'name'=>'Macedonia del Norte',   'created_at' => new DateTime ],
            ['id'=>109, 'name'=>'Madagascar',   'created_at' => new DateTime ],
            ['id'=>110, 'name'=>'Malasia',   'created_at' => new DateTime ],
            ['id'=>111, 'name'=>'Malaui',   'created_at' => new DateTime ],
            ['id'=>112, 'name'=>'Maldivas',   'created_at' => new DateTime ],
            ['id'=>113, 'name'=>'Malí',   'created_at' => new DateTime ],
            ['id'=>114, 'name'=>'Malta',   'created_at' => new DateTime ],
            ['id'=>115, 'name'=>'Marruecos',   'created_at' => new DateTime ],
            ['id'=>116, 'name'=>'Mauricio',   'created_at' => new DateTime ],
            ['id'=>117, 'name'=>'Mauritania',   'created_at' => new DateTime ],
            ['id'=>118, 'name'=>'México',   'created_at' => new DateTime ],
            ['id'=>119, 'name'=>'Micronesia',   'created_at' => new DateTime ],
            ['id'=>120, 'name'=>'Moldavia',   'created_at' => new DateTime ],
            ['id'=>121, 'name'=>'Mónaco',   'created_at' => new DateTime ],
            ['id'=>122, 'name'=>'Mongolia',   'created_at' => new DateTime ],
            ['id'=>123, 'name'=>'Montenegro',   'created_at' => new DateTime ],
            ['id'=>124, 'name'=>'Mozambique',   'created_at' => new DateTime ],
            ['id'=>125, 'name'=>'Namibia',   'created_at' => new DateTime ],
            ['id'=>126, 'name'=>'Nauru',   'created_at' => new DateTime ],
            ['id'=>127, 'name'=>'Nepal',   'created_at' => new DateTime ],
            ['id'=>128, 'name'=>'Nicaragua',   'created_at' => new DateTime ],
            ['id'=>129, 'name'=>'Níger',   'created_at' => new DateTime ],
            ['id'=>130, 'name'=>'Nigeria',   'created_at' => new DateTime ],
            ['id'=>131, 'name'=>'Noruega',   'created_at' => new DateTime ],
            ['id'=>132, 'name'=>'Nueva Zelanda',   'created_at' => new DateTime ],
            ['id'=>133, 'name'=>'Omán',   'created_at' => new DateTime ],
            ['id'=>134, 'name'=>'Países Bajos',   'created_at' => new DateTime ],
            ['id'=>135, 'name'=>'Pakistán',   'created_at' => new DateTime ],
            ['id'=>136, 'name'=>'Palaos',   'created_at' => new DateTime ],
            ['id'=>137, 'name'=>'Panamá',   'created_at' => new DateTime ],
            ['id'=>138, 'name'=>'Papúa Nueva Guinea',   'created_at' => new DateTime ],
            ['id'=>139, 'name'=>'Paraguay',   'created_at' => new DateTime ],
            ['id'=>140, 'name'=>'Perú',   'created_at' => new DateTime ],
            ['id'=>141, 'name'=>'Polonia',   'created_at' => new DateTime ],
            ['id'=>142, 'name'=>'Portugal',   'created_at' => new DateTime ],
            ['id'=>143, 'name'=>'Reino Unido',   'created_at' => new DateTime ],
            ['id'=>144, 'name'=>'República Centroafricana',   'created_at' => new DateTime ],
            ['id'=>145, 'name'=>'República Checa',   'created_at' => new DateTime ],
            ['id'=>146, 'name'=>'República del Congo',   'created_at' => new DateTime ],
            ['id'=>147, 'name'=>'República Democrática del Congo',   'created_at' => new DateTime ],
            ['id'=>148, 'name'=>'República Dominicana',   'created_at' => new DateTime ],
            ['id'=>149, 'name'=>'Ruanda',   'created_at' => new DateTime ],
            ['id'=>150, 'name'=>'Rumanía',   'created_at' => new DateTime ],
            ['id'=>151, 'name'=>'Rusia',   'created_at' => new DateTime ],
            ['id'=>152, 'name'=>'Samoa',   'created_at' => new DateTime ],
            ['id'=>153, 'name'=>'San Cristóbal y Nieves',   'created_at' => new DateTime ],
            ['id'=>154, 'name'=>'San Marino',   'created_at' => new DateTime ],
            ['id'=>155, 'name'=>'San Vicente y las Granadinas',   'created_at' => new DateTime ],
            ['id'=>156, 'name'=>'Santa Lucía',   'created_at' => new DateTime ],
            ['id'=>157, 'name'=>'Santo Tomé y Príncipe',   'created_at' => new DateTime ],
            ['id'=>158, 'name'=>'Senegal',   'created_at' => new DateTime ],
            ['id'=>159, 'name'=>'Serbia',   'created_at' => new DateTime ],
            ['id'=>160, 'name'=>'Seychelles',   'created_at' => new DateTime ],
            ['id'=>161, 'name'=>'Sierra Leona',   'created_at' => new DateTime ],
            ['id'=>162, 'name'=>'Singapur',   'created_at' => new DateTime ],
            ['id'=>163, 'name'=>'Siria',   'created_at' => new DateTime ],
            ['id'=>164, 'name'=>'Somalia',   'created_at' => new DateTime ],
            ['id'=>165, 'name'=>'Sri Lanka',   'created_at' => new DateTime ],
            ['id'=>166, 'name'=>'Suazilandia',   'created_at' => new DateTime ],
            ['id'=>167, 'name'=>'Sudáfrica',   'created_at' => new DateTime ],
            ['id'=>168, 'name'=>'Sudán',   'created_at' => new DateTime ],
            ['id'=>169, 'name'=>'Sudán del Sur',   'created_at' => new DateTime ],
            ['id'=>170, 'name'=>'Suecia',   'created_at' => new DateTime ],
            ['id'=>171, 'name'=>'Suiza',   'created_at' => new DateTime ],
            ['id'=>172, 'name'=>'Surinam',   'created_at' => new DateTime ],
            ['id'=>173, 'name'=>'Tailandia',   'created_at' => new DateTime ],
            ['id'=>174, 'name'=>'Tanzania',   'created_at' => new DateTime ],
            ['id'=>175, 'name'=>'Tayikistán',   'created_at' => new DateTime ],
            ['id'=>176, 'name'=>'Timor Oriental',   'created_at' => new DateTime ],
            ['id'=>177, 'name'=>'Togo',   'created_at' => new DateTime ],
            ['id'=>178, 'name'=>'Tonga',   'created_at' => new DateTime ],
            ['id'=>179, 'name'=>'Trinidad y Tobago',   'created_at' => new DateTime ],
            ['id'=>180, 'name'=>'Túnez',   'created_at' => new DateTime ],
            ['id'=>181, 'name'=>'Turkmenistán',   'created_at' => new DateTime ],
            ['id'=>182, 'name'=>'Turquía',   'created_at' => new DateTime ],
            ['id'=>183, 'name'=>'Tuvalu',   'created_at' => new DateTime ],
            ['id'=>184, 'name'=>'Ucrania',   'created_at' => new DateTime ],
            ['id'=>185, 'name'=>'Uganda',   'created_at' => new DateTime ],
            ['id'=>186, 'name'=>'Uruguay',   'created_at' => new DateTime ],
            ['id'=>187, 'name'=>'Uzbekistán',   'created_at' => new DateTime ],
            ['id'=>188, 'name'=>'Vanuatu',   'created_at' => new DateTime ],
            ['id'=>189, 'name'=>'Venezuela',   'created_at' => new DateTime ],
            ['id'=>190, 'name'=>'Vietnam',   'created_at' => new DateTime ],
            ['id'=>191, 'name'=>'Yemen',   'created_at' => new DateTime ],
            ['id'=>192, 'name'=>'Yibuti',   'created_at' => new DateTime ],
            ['id'=>193, 'name'=>'Zambia',   'created_at' => new DateTime ],
            ['id'=>194, 'name'=>'Zimbabue',   'created_at' => new DateTime ],

          ];

        DB::table('paises')->insert($paises);
        DB::statement('SET FOREIGN_KEY_CHECKS=1');

    }
}
